### ISSUE TITLE
openai.error.InvalidRequestError: An API version is required for the Azure API type.

### ISSUE THREAD

**Issue by junkei-okinawa** [KillianLucas/open-interpreter#719]
### Describe the bug

Although the azure api version is set, the option is not linked to litellm.

### Reproduce

1. setting config`interpreter --config`
```yaml
model: "azure/[my_deproyment_name]"
api_base: "https://my-azure-endpoint.openai.azure.com/"
api_key: "my_azure_api_key"
api_version: "2023-07-01-preview"
```
2. execute interpreter `interpreter --debug_mode` 
3. Execution is interrupted due to an error
```sh
openai.error.InvalidRequestError: An API version is required for the Azure API type.
```

### Expected behavior

I expected the interpreter to run without any errors.

### Open Interpreter version

0.1.10

### Python version

3.11.5

### Operating System name and version

Windows10

### Additional context

`llm\setup_openai_coding_llm.py`の79行目に以下を追記すると問題を解消できる
```diff
        # Optional inputs
        if interpreter.api_base:
            params["api_base"] = interpreter.api_base
        if interpreter.api_key:
            params["api_key"] = interpreter.api_key
+        if interpreter.api_version:
+            params["api_version"] = interpreter.api_version
        if interpreter.max_tokens:
            params["max_tokens"] = interpreter.max_tokens
        if interpreter.temperature:
            params["temperature"] = interpreter.temperature
```
