### ISSUE TITLE
Can not set max_tokens while use gpt-3.5-turbo model.

### ISSUE THREAD

**Issue by aiyogg** [KillianLucas/open-interpreter#812]
### Describe the bug

The max_tokens setting was not working while I used the gpt-3.5-turbo, but it works well when I use the gpt-4 with the same config.

### Reproduce

1. Edit config with `interpreter --config` command.
2. Add these config item: 
 ```yaml
api_base: https://PROXY_TO_OPENAI/v1
api_key: MY_KEY
model: "gpt-3.5-turbo"
# model: "gpt-4"
max_tokens: 80000
context_window: 80000
````
3. Saved config and run `interpreter`
4. Got this Error: `litellm.exceptions.ContextWindowExceededError: This model's maximum context length is 4096 tokens. However, you requested 4829 tokens (631 in the messages, 102 in the functions, and 4096 in the completion). Please reduce the length of the messages, functions, or completion.`

### Expected behavior

`interpreter` request with `max_tokens` and `context_window`  params from my config, not the default params.

### Open Interpreter version

0.1.16

### Python version

3.11.3

### Operating System name and version

macOS-13.3-arm64-arm-64bit
