### ISSUE TITLE
Run commands often missing 2 characters, and repeatedly fails

### ISSUE THREAD

**Issue by JamesClarke7283** [KillianLucas/open-interpreter#934]
### Describe the bug

For example it runs:
`update-desktop-database /home/xxx/.local/are/applications`
Instead of:
`update-desktop-database /home/xxx/.local/share/applications`

And it is known to keep doing this with other commands.

### Reproduce

1. Ask it to run some commands
2. Over time you will see that it runs the incorrect commands spelt wrong by 2 characters, especially with git.

### Expected behavior

It runs the commands spelled correctly most the time, and not arbitrarily missing characters. 

### Open Interpreter version

0.2.0

### Python version

3.11.6

### Operating System name and version

Archlinux

### Additional context

Config file
```yaml
llm.model: "gpt-4-1106-preview"
llm.temperature: 0

custom_instructions: "Please if you are going to view commit history dont view any more than 20 commits in the past, also dont use anything in interactive mode like nano,git rebase --interactive or anything like that, please use shell commands instead of using a graphical environment"

version: 0.2.0 # Configuration file version (do not modify)

```
